### ISSUE TITLE
Doesn't record anything on macOS Ventura

### ISSUE THREAD

**Issue by exislow** [erdewit/HiFiScan#12]
I have installed this app on macOS Ventura 13.0 (Intel MacBook Pro). As soon as the app is started I get this error, when using my onboard loudspeakers and microphone:

```
Error in task:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hifiscan/app.py", line 638, in wrap_coro
    await coro
  File "/usr/local/lib/python3.10/site-packages/hifiscan/app.py", line 47, in analyze
    with hifi.Audio() as audio:
  File "/usr/local/lib/python3.10/site-packages/hifiscan/audio.py", line 24, in __init__
    self.stream = sd.Stream(
  File "/usr/local/lib/python3.10/site-packages/sounddevice.py", line 1800, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "/usr/local/lib/python3.10/site-packages/sounddevice.py", line 811, in __init__
    raise ValueError(
ValueError: Input and output device must have the same samplerate
```

If I start the app with a USB sound card attached, the following error is shown:

```
Error in task:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hifiscan/app.py", line 638, in wrap_coro
    await coro
  File "/usr/local/lib/python3.10/site-packages/hifiscan/app.py", line 47, in analyze
    with hifi.Audio() as audio:
  File "/usr/local/lib/python3.10/site-packages/hifiscan/audio.py", line 24, in __init__
    self.stream = sd.Stream(
  File "/usr/local/lib/python3.10/site-packages/sounddevice.py", line 1800, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "/usr/local/lib/python3.10/site-packages/sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/usr/local/lib/python3.10/site-packages/sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening Stream: Invalid number of channels [PaErrorCode -9998]
```

If I start the app with an USB UMIK-1 attached, I get this error:

```
Error in task:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hifiscan/app.py", line 638, in wrap_coro
    await coro
  File "/usr/local/lib/python3.10/site-packages/hifiscan/app.py", line 47, in analyze
    with hifi.Audio() as audio:
  File "/usr/local/lib/python3.10/site-packages/hifiscan/audio.py", line 24, in __init__
    self.stream = sd.Stream(
  File "/usr/local/lib/python3.10/site-packages/sounddevice.py", line 1800, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "/usr/local/lib/python3.10/site-packages/sounddevice.py", line 811, in __init__
    raise ValueError(
ValueError: Input and output device must have the same samplerate
qt.pointer.dispatch: skipping QEventPoint(id=4 ts=0 pos=0,0 scn=521.818,866.239 gbl=521.818,866.239 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-521.818,-866.239 last=-521.818,-866.239 Δ 521.818,866.239) : no target window
```

If I start the app with the USB sound card and an USB UMIK-1 attached the app starts without error, I can hear a sweeping sound but it does not record anything!

What is going on? 

Is it maybe possible, that add a menu, where I can select the in- and output device and maybe also a button for start recording, instead of just playing the sweeping sound as soon as the app starts? 

Thanks!

**Comment by erdewit** [comment]
It uses the system's default input and output device, which can be set via the OS. The input and output sample rates must also be set to match.
