### ISSUE TITLE
ValueError: Input and output device must have the same samplerate

### ISSUE THREAD

**Issue by pedrospdc** [erdewit/HiFiScan#6]
On my M1 Mac, when starting hifiscan i get:
```
➜  ~ hifiscan
Error in task:
Traceback (most recent call last):
  File "/Users/pedro/.pyenv/versions/3.10.5/envs/playground/lib/python3.10/site-packages/hifiscan/app.py", line 356, in wrap_coro
    await coro
  File "/Users/pedro/.pyenv/versions/3.10.5/envs/playground/lib/python3.10/site-packages/hifiscan/app.py", line 44, in analyze
    with hifi.Audio() as audio:
  File "/Users/pedro/.pyenv/versions/3.10.5/envs/playground/lib/python3.10/site-packages/hifiscan/audio.py", line 26, in __init__
    self.stream = sd.Stream(
  File "/Users/pedro/.pyenv/versions/3.10.5/envs/playground/lib/python3.10/site-packages/sounddevice.py", line 1800, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "/Users/pedro/.pyenv/versions/3.10.5/envs/playground/lib/python3.10/site-packages/sounddevice.py", line 811, in __init__
    raise ValueError(
ValueError: Input and output device must have the same samplerate
```
I have "External Headphones" selected as output, and a Scarlett 2i2 as input. I dont think the samplerate has been customized on my Scarlet.

**Comment by erdewit** [comment]
Have you tried setting the sample rate of the Scarlett to that of the output?

**Comment by erdewit** [comment]
This should be fixed in the latest versions, where that sample rate is set explicitly.
